### ISSUE TITLE
Subtitle text tense is inconsistent

### ISSUE THREAD

**Issue by jdm** [rainshen49/hellocon#1]
Two of the three subtitles are in the imperative, and one is not:
* "Connect with Professionals"
* "Program with Passion"
* "Sharing Exciting Ideas!" - "Share Exciting Ideas!" would fit the pattern better.

**Comment by rainshen49** [comment]
OK. I've told the banner people about this. We will try to make a new banner by Friday night.

**Comment by jdm** [comment]
This subtitle now reads "Share exciting ideas".
