### ISSUE TITLE
Speaker image in banner is misleading

### ISSUE THREAD

**Issue by jdm** [rainshen49/hellocon#3]
I'm on the fence about this - I like the idea of it, but it's not a picture from our conference, and it's not what speaking at our conference will look like (I presume!). My fear is that potential speakers (especially first-time speakers) will see that image and choose not to submit based on it. My inclination is to remove the photo and replace it with something else.

**Comment by rainshen49** [comment]
We actually had quite some discussion about what to put. Initially the speaker's transparent background wasn't there, it was just white. I feel that is OK. But Melinda thinks we need some interesting background. Do you have any thoughts on the "something else" to put there?

**Comment by jdm** [comment]
What about a recognizable photo of Toronto like https://i.ytimg.com/vi/fgbFdV7yL_o/maxresdefault.jpg ?

**Comment by rainshen49** [comment]
That's actually a good idea!
I also find this: https://www.thestar.com/content/dam/thestar/news/city_hall/2016/06/20/funding-woes-could-dim-toronto-signs-glow/cbtorontosign003.jpg
I gave both to the design ppl

**Comment by rainshen49** [comment]
The banner designer decided to keep the background because: "hey rain, I tried changing the background of the poster and it doesnt look as good haha. I feel like without the background, the attendees/speakers would not have much idea about the event through the title "Hello, Con!". By having the image of a speaker with an audience, it shows what kind of an event it is. But took the feedback for the subtitles." and I agree with her because the nature of the conference is a more important information than the location.

**Comment by jdm** [comment]
My fear is that the image may dissuade potential first time or inexperienced speakers who don't want the kind of speaking environment that the image depicts :(

**Comment by rainshen49** [comment]
So you mean the image depiction is too formal for a new speaker?

**Comment by rainshen49** [comment]
what about this http://caylor.eri.ucsb.edu/wp-content/uploads/2013/04/8683849221_c3f632b61d_o.jpg
or any previous photo from !!con: https://twitter.com/bangbangcon/media

**Comment by rainshen49** [comment]
besides the b12c4b715eb51da894fea342eb943972750b3280 commit, we have these two photos:
https://goldenkeyhq.files.wordpress.com/2016/10/networking.jpg
https://techpresentations.files.wordpress.com/2014/08/cropped-presentation.jpg

**Comment by jdm** [comment]
I really like the new banner background! Thanks for following up!

**Comment by rainshen49** [comment]
Great!
