### ISSUE TITLE
Where is the code of conduct from?

### ISSUE THREAD

**Issue by jdm** [rainshen49/hellocon#6]
As far as I can tell, it appears to be a mashup of some of the CoC from http://bangbangcon.com/conduct.html (specifically, the recurse center social rules), and something else that I haven't identified yet. I'm worried by this; there's been a lot of thought put into existing CoCs from other places (like CUSEC's, or the Geek Feminism one), and there's text in the one at http://www.hellocon.net/#code which shows that it has not been read through carefully:
"Harassment includes offensive statement topics include but are not limited to the following topics are not allowed:"
"Inappropriate actions include but are not limited to the following topics are not allowed:"
I think we should use an existing one with the minimal amount of modification necessary, and cite it appropriately at the bottom of the document.

**Comment by rainshen49** [comment]
OK, I'll contact the ppl writing the CoC about this.

**Comment by rainshen49** [comment]
It's updated. How's it now?

**Comment by jdm** [comment]
The bit about `We (the organizers) learned and lifted these rules from the Recurse Center, where we felt that they contributed enormously to a supportive, productive, and fun learning environment.` is misleading, as I suspect none of Hello, Con's organizers have participated in the Recurse Center program. I would recommend instead:
```
We (the organizers) believe that the rules from [the Recurse Center](https://www.recurse.com/) contribute enormously to a supportive, productive, and fun learning environment.
```

**Comment by jdm** [comment]
I would recommend changing `We have learnt the code of conduct from the [!!Con](http://bangbangcon.com/).` to `This Code of Conduct is inspired by the one used by [!!Con](http://bangbangcon.com/). The subject matter is unchanged; only the contact information and conference name have been modified.`

**Comment by jdm** [comment]
Also, the bit about the source of the CoC belongs under the License header, rather than Social Rules.

**Comment by jdm** [comment]
Otherwise this is a good improvement; thanks!

**Comment by jdm** [comment]
Submitted https://github.com/rainshen49/hellocon/pull/7 with my suggestions.
